#!/bin/bash
# Semantic versioning management script for LGX Runtime Core
# Follows Semantic Versioning 2.0.0 (https://semver.org/)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Version file locations
CMAKE_FILE="$PROJECT_ROOT/CMakeLists.txt"
VERSION_HEADER="$PROJECT_ROOT/include/lgx_version.h"
PKGCONFIG_FILE="$PROJECT_ROOT/lgx_runtime.pc.in"
DEB_CHANGELOG="$PROJECT_ROOT/packaging/debian/changelog"
RPM_SPEC="$PROJECT_ROOT/packaging/rpm/lgx-runtime.spec"
ARCH_PKGBUILD="$PROJECT_ROOT/packaging/arch/PKGBUILD"

# Get current version from CMakeLists.txt
get_current_version() {
    if [ -f "$CMAKE_FILE" ]; then
        grep "^project.*VERSION" "$CMAKE_FILE" | sed -n 's/.*VERSION \([0-9.]*\).*/\1/p'
    else
        echo "0.0.0"
    fi
}

# Parse version into components
parse_version() {
    local version=$1
    MAJOR=$(echo "$version" | cut -d. -f1)
    MINOR=$(echo "$version" | cut -d. -f2)
    PATCH=$(echo "$version" | cut -d. -f3)
}

# Validate version format
validate_version() {
    local version=$1
    if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo -e "${RED}Error: Invalid version format: $version${NC}"
        echo "Expected format: MAJOR.MINOR.PATCH (e.g., 1.2.3)"
        return 1
    fi
    return 0
}

# Update CMakeLists.txt
update_cmake() {
    local new_version=$1
    echo -e "${YELLOW}Updating CMakeLists.txt...${NC}"
    sed -i "s/project(lgx_runtime VERSION [0-9.]*/project(lgx_runtime VERSION $new_version/" "$CMAKE_FILE"
}

# Update version header
update_version_header() {
    local major=$1
    local minor=$2
    local patch=$3
    
    echo -e "${YELLOW}Updating include/lgx_version.h...${NC}"
    
    cat > "$VERSION_HEADER" << EOF
#ifndef LGX_VERSION_H
#define LGX_VERSION_H

/**
 * @file lgx_version.h
 * @brief LGX Runtime Core version information
 * 
 * This file is auto-generated by scripts/version.sh
 * Do not edit manually.
 */

#define LGX_VERSION_MAJOR ${major}
#define LGX_VERSION_MINOR ${minor}
#define LGX_VERSION_PATCH ${patch}

#define LGX_VERSION_STRING "${major}.${minor}.${patch}"

/**
 * @brief Compile-time version check macro
 * 
 * Example:
 *   #if LGX_VERSION_AT_LEAST(1, 2, 0)
 *     // Use features from 1.2.0+
 *   #endif
 */
#define LGX_VERSION_AT_LEAST(major, minor, patch) \\
    ((LGX_VERSION_MAJOR > (major)) || \\
     (LGX_VERSION_MAJOR == (major) && LGX_VERSION_MINOR > (minor)) || \\
     (LGX_VERSION_MAJOR == (major) && LGX_VERSION_MINOR == (minor) && LGX_VERSION_PATCH >= (patch)))

/**
 * @brief Encoded version number for runtime comparison
 * 
 * Format: (major * 10000) + (minor * 100) + patch
 * Example: 1.2.3 -> 10203
 */
#define LGX_VERSION_NUMBER ((LGX_VERSION_MAJOR * 10000) + (LGX_VERSION_MINOR * 100) + LGX_VERSION_PATCH)

#endif /* LGX_VERSION_H */
EOF
}

# Update Debian changelog
update_debian_changelog() {
    local new_version=$1
    local message=$2
    
    echo -e "${YELLOW}Updating packaging/debian/changelog...${NC}"
    
    # Create new changelog entry
    local date=$(date -R)
    local temp_file=$(mktemp)
    
    cat > "$temp_file" << EOF
lgx-runtime (${new_version}-1) unstable; urgency=medium

  * Release version ${new_version}
  * ${message}

 -- LGX Platform Team <team@lgx-platform.org>  ${date}

EOF
    
    # Prepend to existing changelog
    if [ -f "$DEB_CHANGELOG" ]; then
        cat "$DEB_CHANGELOG" >> "$temp_file"
    fi
    
    mv "$temp_file" "$DEB_CHANGELOG"
}

# Update RPM spec
update_rpm_spec() {
    local new_version=$1
    local message=$2
    
    echo -e "${YELLOW}Updating packaging/rpm/lgx-runtime.spec...${NC}"
    
    # Update Version field
    sed -i "s/^Version:.*/Version:        ${new_version}/" "$RPM_SPEC"
    
    # Add changelog entry
    local date=$(date "+%a %b %d %Y")
    local temp_file=$(mktemp)
    
    # Extract everything before %changelog
    sed -n '1,/%changelog/p' "$RPM_SPEC" > "$temp_file"
    
    # Add new changelog entry
    cat >> "$temp_file" << EOF
* ${date} LGX Platform Team <team@lgx-platform.org> - ${new_version}-1
- Release version ${new_version}
- ${message}

EOF
    
    # Add existing changelog entries (skip the %changelog line)
    sed -n '/%changelog/,$ {/%changelog/!p}' "$RPM_SPEC" >> "$temp_file"
    
    mv "$temp_file" "$RPM_SPEC"
}

# Update Arch PKGBUILD
update_arch_pkgbuild() {
    local new_version=$1
    
    echo -e "${YELLOW}Updating packaging/arch/PKGBUILD...${NC}"
    
    sed -i "s/^pkgver=.*/pkgver=${new_version}/" "$ARCH_PKGBUILD"
    sed -i "s/^pkgrel=.*/pkgrel=1/" "$ARCH_PKGBUILD"
}

# Update .SRCINFO for AUR
update_srcinfo() {
    local new_version=$1
    
    echo -e "${YELLOW}Updating packaging/arch/.SRCINFO...${NC}"
    
    local srcinfo_file="$PROJECT_ROOT/packaging/arch/.SRCINFO"
    
    sed -i "s/pkgver = .*/pkgver = ${new_version}/" "$srcinfo_file"
    sed -i "s/pkgrel = .*/pkgrel = 1/" "$srcinfo_file"
    sed -i "s|source = lgx-runtime-.*\.tar\.gz|source = lgx-runtime-${new_version}.tar.gz::https://github.com/lgx-platform/LGX/archive/v${new_version}.tar.gz|" "$srcinfo_file"
}

# Bump version
bump_version() {
    local bump_type=$1
    local current_version=$(get_current_version)
    
    parse_version "$current_version"
    
    case $bump_type in
        major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
        minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
        patch)
            PATCH=$((PATCH + 1))
            ;;
        *)
            echo -e "${RED}Error: Invalid bump type: $bump_type${NC}"
            echo "Valid types: major, minor, patch"
            exit 1
            ;;
    esac
    
    echo "$MAJOR.$MINOR.$PATCH"
}

# Set version
set_version() {
    local new_version=$1
    local message=${2:-"Version bump to $new_version"}
    
    if ! validate_version "$new_version"; then
        exit 1
    fi
    
    local current_version=$(get_current_version)
    
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║         LGX Runtime Core - Version Update                 ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${YELLOW}Current version:${NC} $current_version"
    echo -e "${YELLOW}New version:${NC}     $new_version"
    echo -e "${YELLOW}Message:${NC}         $message"
    echo ""
    
    read -p "Continue? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
    
    parse_version "$new_version"
    
    # Update all version files
    update_cmake "$new_version"
    update_version_header "$MAJOR" "$MINOR" "$PATCH"
    update_debian_changelog "$new_version" "$message"
    update_rpm_spec "$new_version" "$message"
    update_arch_pkgbuild "$new_version"
    update_srcinfo "$new_version"
    
    echo ""
    echo -e "${GREEN}✓ Version updated to $new_version${NC}"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Review changes: git diff"
    echo "  2. Commit changes: git add -A && git commit -m 'Bump version to $new_version'"
    echo "  3. Create tag: git tag -a v$new_version -m 'Release $new_version'"
    echo "  4. Push changes: git push && git push --tags"
    echo "  5. Create release: scripts/release.sh $new_version"
}

# Show current version
show_version() {
    local current_version=$(get_current_version)
    echo "$current_version"
}

# Show usage
usage() {
    cat << EOF
Usage: $0 <command> [options]

Commands:
  show                    Show current version
  set <version> [msg]     Set specific version (e.g., 1.2.3)
  bump <type> [msg]       Bump version (type: major, minor, patch)
  
Examples:
  $0 show
  $0 set 1.2.3 "Release 1.2.3 with new features"
  $0 bump minor "Add new API functions"
  $0 bump patch "Fix memory leak"

Semantic Versioning:
  MAJOR: Incompatible API changes
  MINOR: Backwards-compatible functionality additions
  PATCH: Backwards-compatible bug fixes

EOF
}

# Main
main() {
    if [ $# -eq 0 ]; then
        usage
        exit 1
    fi
    
    case $1 in
        show)
            show_version
            ;;
        set)
            if [ $# -lt 2 ]; then
                echo -e "${RED}Error: Missing version argument${NC}"
                usage
                exit 1
            fi
            set_version "$2" "${3:-Version bump to $2}"
            ;;
        bump)
            if [ $# -lt 2 ]; then
                echo -e "${RED}Error: Missing bump type${NC}"
                usage
                exit 1
            fi
            new_version=$(bump_version "$2")
            set_version "$new_version" "${3:-Bump $2 version to $new_version}"
            ;;
        *)
            echo -e "${RED}Error: Unknown command: $1${NC}"
            usage
            exit 1
            ;;
    esac
}

main "$@"
